try

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,15 +19,18 @@ jobs:
       # needs: linux-x86_64-cmake
     runs-on: faiss-aws-m5.xlarge
     steps:
+      # - name: Checkout
+      #   continue-on-error: true
+      #   uses: actions/checkout@v4
+      # - name: Try to fail
+      #   continue-on-error: true
+      #   run: exit 1
+      # - name: Print message if we don't fail
+      #   run: echo Should not get here
+
       - name: Checkout
         continue-on-error: true
         uses: actions/checkout@v4
-      - name: Try to fail
-        continue-on-error: true
-        run: exit 1
-      - name: Print message if we don't fail
-        run: echo Should not get here
-
-      # - uses: ./.github/actions/build_cmake
-      #  with:
-      #    opt_level: avx512
+      - uses: ./.github/actions/build_cmake
+       with:
+         opt_level: avx512
